// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FuncProxyURI is an autogenerated mock type for the FuncProxyURI type
type FuncProxyURI struct {
	mock.Mock
}

// Execute provides a mock function with given fields: filePath, commit
func (_m *FuncProxyURI) Execute(filePath string, commit string) string {
	ret := _m.Called(filePath, commit)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(filePath, commit)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewFuncProxyURI creates a new instance of FuncProxyURI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFuncProxyURI(t interface {
	mock.TestingT
	Cleanup(func())
}) *FuncProxyURI {
	mock := &FuncProxyURI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
